### ISSUE TITLE
Fatal error detected: "Failed to execute script answer"

### ISSUE THREAD

**Issue by mike-lowski** [pauloBFalmeida/GTAO_finger_print_script#1]
When pressing the shortcuts for the finger print hack it displays this warning. All files are in the same folder. The other 2 shorcuts work.

**Comment by pauloBFalmeida** [comment]
Ops so sorry, i didnt update or organize yet, but the folder download contains the most recently correct files, but if this one doesn't work you can look at this other script https://www.reddit.com/r/gtaglitches/comments/hd52z1/improved_fingerprint_solver/ that other people are working on maybe it will work :3

**Comment by mike-lowski** [comment]
Couldn't get it to work, keeps showing this warning, tried in other pc too. The reddit scripts didn't work either, I guess I'll have to keep solving it by hand.
